### PR TITLE
adding support for 0.33 and 0.34

### PR DESCRIPTION
**Pull request by wspi**
Adding support for the lastest enterprise versions

### CODE REVIEW

**Comment by Maples7** [comment]
Any details about enterprise edition from the official website of Kong? I myself don't use enterprise edition. If there are some public resource about it, I'll try to cover the support or find some other way to solve the compatibility problem once for all.  

By the way, your PR gets syntax error which can not be merged for now. And I wonder if it's the best way to solve the compatibility problem.

**Comment by Maples7** [comment]
In addition, please make use of [the `objects` filed in the config file](https://github.com/Maples7/kong-config-manager#cli-configuration-file) to customize your own objects

**Comment by wspi** [comment]
I don't  think there is anything explicit on the kong website besides this https://konghq.com/kong-enterprise/  but the main difference is the support, custom plugins, and a web gui to manage kong.

The reason I didn't updated the objects, is because kong enterprise 0.33 is the same as kong 0.13, kong-ee 0.34 is the same as 0.14... they just add some plugins, so as the objects are the same, I was just reusing the code.

and last, there was a typo, sorry, I'm pushing the new code

**Comment by wspi** [comment]
maybe, another approach could be a map of enterprise versions -> community versions

**Comment by Maples7** [comment]
```javascript
var version;
if (res.version.endsWith("enterprise-edition")) {
  version = res.version.replace("-enterprise-edition", ".0");
} else {
  version = res.version;
}
```
Based on no more explicit explain about the relationship of versions between CE(Community Edition) and EE(Enterprise Edition), I'd like to assume the logic of code above is right which is more common than a hard-coding mapping.

**Comment by Maples7** [comment]
Checkout v1.6.2 to see if it works.

**Pull request merged**
