### PR TITLE
Support for insecure endpoints

### PR DESCRIPTION
**Pull request by azachar**
Hello, 

I have implemented a brand new option -k (--no-ssl) that allows you to connect to self signed kong instance without ssl checks. 

I did also a test for it by upgrading nested project, where I open 2 ports  (3001 for http and 3443 for https).

I look forward for your review.

Best regards,
Andrej

PS: Feel free to squash all my commits into a one

### CODE REVIEW

**Comment by azachar** [comment]
Please note that I am still working on tests, hopefully soon I will have them done. So far I am expecting you valuable review.

**Comment by Maples7** [comment]
Awesome job! So many thanks for your contribution! I'll check the PR and look forward to your work on tests~ 👍

**Comment by azachar** [comment]
Dear @maples7,

Now all the tests are running fine. You need to upgrade the nested project too. Since we need a test ssl endpoint. If you want I can squash commits together and rebase it on your master and force push this PR. Let me know, how to proceed. 

Cheers,
Andrej

**Comment by Maples7** [comment]
So sorry for being so late to review your PR. I've been busy these days. 

The good new is I've released a new edition which covers `--no-ssl` feature. Thanks again! 💯

**Pull request merged**
